version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    versioning-strategy: auto
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    versioning-strategy: auto
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    open-pull-requests-limit: 10
